=== LordKiRon/fb2epub/Fb2ePub/Translit/translit.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns="http://www.lordkiron.com/translit" 
targetNamespace="http://www.lordkiron.com/translit"
elementFormDefault="qualified">

<xs:element name="transtable">
  <xs:annotation>
    <xs:documentation>Root element of the file</xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="map"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="map" >
  <xs:annotation>
    <xs:documentation>Single element defining one mapping from cyrillic character to english string</xs:documentation>
  </xs:annotation>
    <xs:complexType>
      <xs:attribute name="in" type="character" use="required"/>
      <xs:attribute name="out" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

  <xs:simpleType name="character">
    <xs:annotation>
      <xs:documentation>Defines type for element containing only one character</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:length value="1"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== LordKiRon/fb2epub/Fb2ePub/Translit/translit.xml
<?xml version="1.0" encoding="UTF-8"?>
<transtable
xmlns="http://www.lordkiron.com/translit"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.lordkiron.com/translit translit.xsd">
<map in='а' out="a"/>
<map in='А' out="A"/>
<map in='б' out="b"/>
<map in='Б' out="B"/>
<map in='в' out="v"/>
<map in='В' out="V"/>
<map in='г' out="g"/>
<map in='Г' out="G"/>
<map in='д' out="d"/>
<map in='Д' out="D"/>
<map in='е' out="e"/>
<map in='Е' out="E"/>
<map in='ё' out="jo"/>
<map in='Ё' out="Jo"/>
<map in='ж' out="zh"/>
<map in='Ж' out="Zh"/>
<map in='з' out="z"/>
<map in='З' out="Z"/>
<map in='и' out="i"/>
<map in='И' out="I"/>
<map in='й' out="j"/>
<map in='Й' out="J"/>
<map in='к' out="k"/>
<map in='К' out="K"/>
<map in='л' out="l"/>
<map in='Л' out="L"/>
<map in='м' out="m"/>
<map in='М' out="M"/>
<map in='н' out="n"/>
<map in='Н' out="N"/>
<map in='о' out="o"/>
<map in='О' out="O"/>
<map in='п' out="p"/>
<map in='П' out="P"/>
<map in='р' out="r"/>
<map in='Р' out="R"/>
<map in='с' out="s"/>
<map in='С' out="S"/>
<map in='т' out="t"/>
<map in='Т' out="T"/>
<map in='у' out="u"/>
<map in='У' out="U"/>
<map in='ф' out="f"/>
<map in='Ф' out="F"/>
<map in='х' out="x"/>
<map in='Х' out="X"/>
<map in='ц' out="c"/>
<map in='Ц' out="C"/>
<map in='ч' out="ch"/>
<map in='Ч' out="Ch"/>
<map in='ш' out="sh"/>
<map in='Ш' out="Sh"/>
<map in='ь' out="'"/>
<map in='Ь' out="'"/>
<map in='ъ' out="#"/>
<map in='Ъ' out="##"/>
<map in='ы' out="y"/>
<map in='Ы' out="Y"/>
<map in='э' out="je"/>
<map in='Э' out="Je"/>
<map in='ю' out="ju"/>
<map in='Ю' out="Ju"/>
<map in='я' out="ja"/>
<map in='Я' out="Ja"/>
<map in='щ' out="w"/>
<map in='Щ' out="W"/>
</transtable>
